//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Mech : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single PullAbility
        {
            get
            {
                return SteamVR_Actions.mech_PullAbility;
            }
        }
        
        public virtual SteamVR_Action_Boolean Shield
        {
            get
            {
                return SteamVR_Actions.mech_Shield;
            }
        }
        
        public virtual SteamVR_Action_Boolean PullAbilityConfirm
        {
            get
            {
                return SteamVR_Actions.mech_PullAbilityConfirm;
            }
        }
        
        public virtual SteamVR_Action_Pose pose
        {
            get
            {
                return SteamVR_Actions.mech_pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration HapticLeft
        {
            get
            {
                return SteamVR_Actions.mech_HapticLeft;
            }
        }
        
        public virtual SteamVR_Action_Vibration HapticRight
        {
            get
            {
                return SteamVR_Actions.mech_HapticRight;
            }
        }
    }
}
